language: scala

jdk:
  # sbt 1 does not support JDK 7 or below: https://github.com/sbt/sbt/issues/4219
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk-ea
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea

scala:
  - 2.11.12
  - 2.12.6

matrix:
  allow_failures:
    - jdk: oraclejdk11
    - jdk: oraclejdk-ea
    - jdk: openjdk11
    - jdk: openjdk-ea

branches:
  only:
    master

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt updateImpactSubmit coverageReport coverageAggregate codacyCoverage makeSite +publish
    on:
      jdk: oraclejdk8
      scala: 2.12.6

  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: target/site
    verbose: true
    on:
      jdk: oraclejdk8
      scala: 2.12.6

  - provider: script
    skip_cleanup: true
    script: curl -s https://codecov.io/bash | bash
    on:
      jdk: oraclejdk8
      scala: 2.12.6

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
