language: scala
jdk:
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk-ea
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea

branches:
  only:
    master

matrix:
  allow_failures:
    - jdk: oraclejdk11
    - jdk: oraclejdk-ea
    - jdk: openjdk7
    - jdk: openjdk11
    - jdk: openjdk-ea

script: sbt clean coverage +test

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt updateImpactSubmit coverageReport coverageAggregate codacyCoverage makeSite +publish

  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: target/site
    verbose: true
    on:
      jdk: oraclejdk8

  - provider: script
    skip_cleanup: true
    script: curl -s https://codecov.io/bash | bash
    on:
      jdk: oraclejdk8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
