language: scala
jdk: oraclejdk8

env:
  global:
    - SBT_GHPAGES_COMMIT_MESSAGE='Publishing Scaladoc [ci skip]'
    - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M -Xmx2G"

script: sbt clean coverage +test

deploy:
  - provider: script
    skip_cleanup: true
    #script: sbt updateImpactSubmit coverageReport coverageAggregate codacyCoverage makeSite
    script: sbt updateImpactSubmit coverageReport coverageAggregate makeSite
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash <(curl -s https://codecov.io/bash)
    on:
      branch: master

  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: target/site
    verbose: true
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: sbt +publish
    on:
      branch: master

# Copied from https://github.com/typelevel/cats/blob/master/.travis.yml
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
  - $HOME/.m2
