language: scala
jdk: oraclejdk8

env:
  global:
    - SBT_GHPAGES_COMMIT_MESSAGE='Publishing Scaladoc [ci skip]'
    - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M -Xmx2G"

script: sbt clean checkFormat coverage +test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      sbt updateImpactSubmit coverageReport coverageAggregate codacyCoverage
      bash <(curl -s https://codecov.io/bash)
      git config --global user.email "pathikritbhowmick@msn.com"
      git config --global user.name "travis-ci"
      git config --global push.default simple
      sbt ghpagesPushSite +publish
    fi

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.m2

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache    -name "ivydata-*.properties"      -print -delete
  - find $HOME/.sbt           -name "*.lock"                    -print -delete
  - find $HOME/.sbt/ghpages   -type d                           -print -delete
