language: scala
jdk: oraclejdk8

env:
  global:
    - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M -Xmx2G"

script: sbt clean coverage +test

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt updateImpactSubmit coverageReport coverageAggregate codacyCoverage makeSite +publish

  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: target/site
    verbose: true

  - provider: script
    skip_cleanup: true
    script: curl -s https://codecov.io/bash | bash

# Copied from https://github.com/typelevel/cats/blob/master/.travis.yml
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
  - $HOME/.m2
